enableArrows = true
enableBows = true
enableHalfBows = true
enableCrossbows = true
enableGauntlets = true
enableQuivers = true
enableShields = true
enableWeapons = true
crossbowVelocityBonus = 0.5
bowRecipeType = "SMITHING_ONLY"
enableFletchingTable = true

[shieldProtectionConfig]
EnableVanillaStyleShieldProtection = false
EnableShieldBaseProtection = true
shieldBaseProtectionType = "DURABILITY_PERCENTAGE"
EnableShieldProtectionPercentage = true

[battlestaff]
durabilityMultiplier = 0.9
baseAttackDamage = -2
attackSpeed = -1.4
mendingBonus = 0.1
knockback = 1.0
attackRange = 1.5
wieldType = "TWOHANDED"

[broadsword]
durabilityMultiplier = 1.1
baseAttackDamage = 3
attackSpeed = -3.0
mendingBonus = 0.0
knockback = 0.0
attackRange = 0.5
wieldType = "ONEHANDED"

[claymore]
durabilityMultiplier = 1.1
baseAttackDamage = 2
attackSpeed = -3.0
mendingBonus = 0.0
knockback = 0.0
attackRange = 1.0
wieldType = "TWOHANDED"

[cutlass]
durabilityMultiplier = 1.0
baseAttackDamage = 0
attackSpeed = -2.2
mendingBonus = 0.2
knockback = 0.0
attackRange = 0.0
wieldType = "ONEHANDED"

[dagger]
durabilityMultiplier = 0.75
baseAttackDamage = -1
attackSpeed = -1.2
mendingBonus = 0.1
knockback = 0.0
attackRange = 0.0
wieldType = "DUALWIELD"

[dancers_sword]
durabilityMultiplier = 1.3
baseAttackDamage = 2
attackSpeed = -1.8
mendingBonus = 0.2
knockback = 0.0
attackRange = 0.0
wieldType = "ONEHANDED"

[flail]
durabilityMultiplier = 1.1
baseAttackDamage = 4
attackSpeed = -3.4
mendingBonus = 0.0
knockback = 0.5
attackRange = 1.0
wieldType = "ONEHANDED"

[glaive]
durabilityMultiplier = 1.0
baseAttackDamage = 3
attackSpeed = -3.2
mendingBonus = 0.1
knockback = 0.5
attackRange = 2.0
wieldType = "TWOHANDED"

[great_hammer]
durabilityMultiplier = 1.5
baseAttackDamage = 5
attackSpeed = -3.3
mendingBonus = 0.0
knockback = 1.0
attackRange = 0.0
wieldType = "ONEHANDED"

[katana]
durabilityMultiplier = 1.0
baseAttackDamage = 2
attackSpeed = -2.4
mendingBonus = 0.0
knockback = 0.0
attackRange = 0.5
wieldType = "ONEHANDED"

[mace]
durabilityMultiplier = 1.1
baseAttackDamage = 4
attackSpeed = -3.2
mendingBonus = 0.0
knockback = 0.5
attackRange = 0.0
wieldType = "ONEHANDED"

[scythe]
durabilityMultiplier = 1.2
baseAttackDamage = 4
attackSpeed = -3.4
mendingBonus = 0.1
knockback = 1.0
attackRange = 2.0
wieldType = "TWOHANDED"

[sickle]
durabilityMultiplier = 0.8
baseAttackDamage = 0
attackSpeed = -1.8
mendingBonus = 0.2
knockback = 0.0
attackRange = 0.0
wieldType = "DUALWIELD"

[spear]
durabilityMultiplier = 1.0
baseAttackDamage = 3
attackSpeed = -3.4
mendingBonus = 0.1
knockback = 0.5
attackRange = 2.0
wieldType = "TWOHANDED"

[vanilla]
equipSound = "minecraft:item.armor.equip_leather"
mendingBonus = 0.0
fireResistant = false
quiverSlots = 0

[vanilla.durability]
toolDurability = 59
bowDurability = 0
addedShieldDurability = 0

[vanilla.enchanting]
offenseEnchantability = 15
defenseEnchantability = 15

[vanilla.offense]
addedAttackDamage = 0.0
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[vanilla.defense]
gauntletArmorAmount = 1
armorToughness = 0.0
knockbackResistance = 0.0
baseProtectionAmmount = 2.5
afterBasePercentReduction = 0.3

[vanilla.crafting]
repairItem = ["minecraft:barrier"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[leather]
equipSound = "minecraft:item.armor.equip_leather"
mendingBonus = 0.0
fireResistant = false
quiverSlots = 2

[leather.durability]
toolDurability = 131
bowDurability = 0
addedShieldDurability = 80

[leather.enchanting]
offenseEnchantability = 5
defenseEnchantability = 15

[leather.offense]
addedAttackDamage = 1.0
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[leather.defense]
gauntletArmorAmount = 1
armorToughness = 0.0
knockbackResistance = 0.0
baseProtectionAmmount = 3.0
afterBasePercentReduction = 0.5

[leather.crafting]
repairItem = ["minecraft:leather"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[iron]
equipSound = "minecraft:item.armor.equip_iron"
mendingBonus = 0.0
fireResistant = false
quiverSlots = 4

[iron.durability]
toolDurability = 250
bowDurability = 480
addedShieldDurability = 150

[iron.enchanting]
offenseEnchantability = 14
defenseEnchantability = 9

[iron.offense]
addedAttackDamage = 2.0
arrowDamage = 3.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 3.0

[iron.defense]
gauntletArmorAmount = 2
armorToughness = 0.0
knockbackResistance = 0.0
baseProtectionAmmount = 3.0
afterBasePercentReduction = 0.6

[iron.crafting]
repairItem = ["minecraft:iron_ingot"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[gold]
equipSound = "minecraft:item.armor.equip_gold"
mendingBonus = 2.0
fireResistant = false
quiverSlots = 6

[gold.durability]
toolDurability = 32
bowDurability = 395
addedShieldDurability = 40

[gold.enchanting]
offenseEnchantability = 22
defenseEnchantability = 25

[gold.offense]
addedAttackDamage = 0.0
arrowDamage = 2.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 2.5

[gold.defense]
gauntletArmorAmount = 1
armorToughness = 0.0
knockbackResistance = 0.0
baseProtectionAmmount = 3.0
afterBasePercentReduction = 0.4

[gold.crafting]
repairItem = ["minecraft:gold_ingot"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[diamond]
equipSound = "minecraft:item.armor.equip_diamond"
mendingBonus = -0.1
fireResistant = false
quiverSlots = 8

[diamond.durability]
toolDurability = 1561
bowDurability = 672
addedShieldDurability = 300

[diamond.enchanting]
offenseEnchantability = 10
defenseEnchantability = 10

[diamond.offense]
addedAttackDamage = 3.0
arrowDamage = 3.75
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 1
velocityMultiplier = 3.5

[diamond.defense]
gauntletArmorAmount = 3
armorToughness = 2.0
knockbackResistance = 0.0
baseProtectionAmmount = 5.0
afterBasePercentReduction = 0.75

[diamond.crafting]
repairItem = ["minecraft:diamond"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[netherite]
equipSound = "minecraft:item.armor.equip_netherite"
mendingBonus = 0.2
fireResistant = true
quiverSlots = 10

[netherite.durability]
toolDurability = 2031
bowDurability = 768
addedShieldDurability = 375

[netherite.enchanting]
offenseEnchantability = 15
defenseEnchantability = 15

[netherite.offense]
addedAttackDamage = 4.0
arrowDamage = 4.5
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 1
velocityMultiplier = 4.0

[netherite.defense]
gauntletArmorAmount = 3
armorToughness = 3.0
knockbackResistance = 0.10000000149011612
baseProtectionAmmount = 6.0
afterBasePercentReduction = 0.85

[netherite.crafting]
repairItem = ["minecraft:netherite_ingot"]
isSingleAddition = true
onlyReplaceResource = ["Diamond"]
smithingTemplate = "minecraft:netherite_upgrade_smithing_template"

[steel]
equipSound = "minecraft:item.armor.equip_iron"
mendingBonus = 0.0
fireResistant = false
quiverSlots = 0

[steel.durability]
toolDurability = 482
bowDurability = 0
addedShieldDurability = 200

[steel.enchanting]
offenseEnchantability = 9
defenseEnchantability = 9

[steel.offense]
addedAttackDamage = 2.5
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[steel.defense]
gauntletArmorAmount = 2
armorToughness = 1.0
knockbackResistance = 0.0
baseProtectionAmmount = 3.5
afterBasePercentReduction = 0.65

[steel.crafting]
repairItem = ["minecraft:barrier"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[bronze]
equipSound = "minecraft:item.armor.equip_generic"
mendingBonus = 0.1
fireResistant = false
quiverSlots = 0

[bronze.durability]
toolDurability = 225
bowDurability = 0
addedShieldDurability = 125

[bronze.enchanting]
offenseEnchantability = 8
defenseEnchantability = 8

[bronze.offense]
addedAttackDamage = 2.0
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[bronze.defense]
gauntletArmorAmount = 2
armorToughness = 0.5
knockbackResistance = 0.0
baseProtectionAmmount = 2.75
afterBasePercentReduction = 0.5

[bronze.crafting]
repairItem = ["minecraft:barrier"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[silver]
equipSound = "minecraft:item.armor.equip_generic"
mendingBonus = 1.0
fireResistant = false
quiverSlots = 0

[silver.durability]
toolDurability = 325
bowDurability = 0
addedShieldDurability = 175

[silver.enchanting]
offenseEnchantability = 18
defenseEnchantability = 18

[silver.offense]
addedAttackDamage = 1.0
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[silver.defense]
gauntletArmorAmount = 2
armorToughness = 0.0
knockbackResistance = 0.0
baseProtectionAmmount = 2.5
afterBasePercentReduction = 0.4

[silver.crafting]
repairItem = ["minecraft:barrier"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[lead]
equipSound = "minecraft:item.armor.equip_generic"
mendingBonus = 0.1
fireResistant = false
quiverSlots = 0

[lead.durability]
toolDurability = 1761
bowDurability = 0
addedShieldDurability = 350

[lead.enchanting]
offenseEnchantability = 8
defenseEnchantability = 8

[lead.offense]
addedAttackDamage = 3.0
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[lead.defense]
gauntletArmorAmount = 3
armorToughness = 0.25
knockbackResistance = 0.5
baseProtectionAmmount = 5.0
afterBasePercentReduction = 0.6

[lead.crafting]
repairItem = ["minecraft:barrier"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[nagaScale]
equipSound = "minecraft:item.armor.equip_generic"
mendingBonus = 0.1
fireResistant = false
quiverSlots = 0

[nagaScale.durability]
toolDurability = 537
bowDurability = 0
addedShieldDurability = 260

[nagaScale.enchanting]
offenseEnchantability = 0
defenseEnchantability = 15

[nagaScale.offense]
addedAttackDamage = 2.0999999046325684
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[nagaScale.defense]
gauntletArmorAmount = 3
armorToughness = 0.5
knockbackResistance = 0.0
baseProtectionAmmount = 4.0
afterBasePercentReduction = 0.65

[nagaScale.crafting]
repairItem = ["twilightforest:naga_scale"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[arctic]
equipSound = "minecraft:item.armor.equip_generic"
mendingBonus = 0.0
fireResistant = false
quiverSlots = 0

[arctic.durability]
toolDurability = 131
bowDurability = 0
addedShieldDurability = 130

[arctic.enchanting]
offenseEnchantability = 0
defenseEnchantability = 8

[arctic.offense]
addedAttackDamage = 2.0
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[arctic.defense]
gauntletArmorAmount = 2
armorToughness = 2.0
knockbackResistance = 0.0
baseProtectionAmmount = 3.0
afterBasePercentReduction = 0.55

[arctic.crafting]
repairItem = ["twilightforest:arctic_fur"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[yeti]
equipSound = "minecraft:item.armor.equip_generic"
mendingBonus = 0.0
fireResistant = false
quiverSlots = 0

[yeti.durability]
toolDurability = 512
bowDurability = 0
addedShieldDurability = 250

[yeti.enchanting]
offenseEnchantability = 0
defenseEnchantability = 15

[yeti.offense]
addedAttackDamage = 2.5
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[yeti.defense]
gauntletArmorAmount = 3
armorToughness = 3.0
knockbackResistance = 0.0
baseProtectionAmmount = 3.5
afterBasePercentReduction = 0.65

[yeti.crafting]
repairItem = ["twilightforest:alpha_yeti_fur"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[ironwood]
equipSound = "minecraft:item.armor.equip_generic"
mendingBonus = 1.5
fireResistant = false
quiverSlots = 0

[ironwood.durability]
toolDurability = 512
bowDurability = 0
addedShieldDurability = 250

[ironwood.enchanting]
offenseEnchantability = 25
defenseEnchantability = 15

[ironwood.offense]
addedAttackDamage = 2.0
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[ironwood.defense]
gauntletArmorAmount = 2
armorToughness = 0.0
knockbackResistance = 0.0
baseProtectionAmmount = 3.5
afterBasePercentReduction = 0.6

[ironwood.crafting]
repairItem = ["twilightforest:ironwood_ingot"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[fiery]
equipSound = "minecraft:item.armor.equip_generic"
mendingBonus = 0.0
fireResistant = false
quiverSlots = 0

[fiery.durability]
toolDurability = 1024
bowDurability = 0
addedShieldDurability = 275

[fiery.enchanting]
offenseEnchantability = 10
defenseEnchantability = 10

[fiery.offense]
addedAttackDamage = 4.0
arrowDamage = 0.0
flaming = true
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[fiery.defense]
gauntletArmorAmount = 4
armorToughness = 1.5
knockbackResistance = 0.0
baseProtectionAmmount = 4.5
afterBasePercentReduction = 0.7

[fiery.crafting]
repairItem = ["twilightforest:steeleaf_ingot"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[steeleaf]
equipSound = "minecraft:item.armor.equip_generic"
mendingBonus = 0.0
fireResistant = false
quiverSlots = 0

[steeleaf.durability]
toolDurability = 131
bowDurability = 0
addedShieldDurability = 180

[steeleaf.enchanting]
offenseEnchantability = 9
defenseEnchantability = 9

[steeleaf.offense]
addedAttackDamage = 3.0
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[steeleaf.defense]
gauntletArmorAmount = 3
armorToughness = 0.0
knockbackResistance = 0.0
baseProtectionAmmount = 3.5
afterBasePercentReduction = 0.6

[steeleaf.crafting]
repairItem = ["twilightforest:steeleaf_ingot"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"

[knightmetal]
equipSound = "twilightforest:item.twilightforest.armor.equip_knightmetal"
mendingBonus = 0.0
fireResistant = false
quiverSlots = 0

[knightmetal.durability]
toolDurability = 512
bowDurability = 0
addedShieldDurability = 250

[knightmetal.enchanting]
offenseEnchantability = 8
defenseEnchantability = 8

[knightmetal.offense]
addedAttackDamage = 3.0
arrowDamage = 0.0
flaming = false
canBeTipped = true
multishotLevel = 0
bowPower = 0
velocityMultiplier = 1.0

[knightmetal.defense]
gauntletArmorAmount = 3
armorToughness = 1.0
knockbackResistance = 0.0
baseProtectionAmmount = 4.0
afterBasePercentReduction = 0.6

[knightmetal.crafting]
repairItem = ["twilightforest:knightmetal_ingot"]
isSingleAddition = false
onlyReplaceResource = []
smithingTemplate = "minecraft:air"
